export default {
  adminToken:
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo0LCJlbWFpbCI6ImZyYW5rQGdtYWlsLmNvbSIsImZpcnN0X25hbWUiOiJGcmFuayIsImxhc3RfbmFtZSI6IkZyYW5rIiwiaXNfYWRtaW4iOnRydWV9LCJpYXQiOjE1NjMwNTIyNjJ9.s5L-N5La4tjxcHjHziaDWFrYfLqTQqZLwSeMyOKilPw",
  userToken:
    "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo3LCJlbWFpbCI6ImF5QGdtYWlsLmNvbSIsImZpcnN0X25hbWUiOiJheSIsImxhc3RfbmFtZSI6InlheWEiLCJpc19hZG1pbiI6ZmFsc2V9LCJpYXQiOjE1NjI4OTAxNTJ9.3JsoPCLVZ_ayad0s1rLfOvoZXhIoa7vVmNZZdMA_pJ4"
};
